[data]
name = "name"
score = "score"
marks = 'marks'
inputstring = 'Illuminex Limited8'
endswith = '8'
replacedstring = 'replaced'
substring = 'i'
value1 = '5'
value2 = '30'
value3 = '35'
value4 = '25'
value5 = '3'
value6 = '2'
inputdate = 'isoFormaWrong'
date1 = '2000-10-31 01:30:00.000000000'
date2 = '2000-11-01 01:30:00.000000000'
regex = 'owl*'
newname = 'slno'
res = 'result'
unit = 'DAY'
date = 'Date'
prefix = 'res'
substring2 = 'Illuminex'
inputdate2 = 'isoFormatRight'
delimeter = 'T'
delimeter2 = '-'
length = '10'
mean = 'MEAN'
